model_name: "celebvhq_marlin_deepfake_ft"
backbone: "marlin_vit_base_ytf"
dataset: "celebvhq"
task: "deepfake"
temporal_reduction: "mean"
learning_rate: 0.80e-3
seq_mean_pool: true
finetune: true
ir_layers: "conv"
num_heads: 1
temporal_axis: 10
