model_name: "celebvhq_marlin_deepfake_ft"
backbone: "marlin_vit_small_ytf"
training_datasets: ["DFDC"] #DeepfakeTIMIT,RAVDESS, Forensics++, DFDC, FakeAVCeleb
eval_datasets: ["DFDC"]
task: "deepfake"
temporal_reduction: "mean"
learning_rate: 1.00e-3
seq_mean_pool: true
finetune: false
ir_layers: "conv"
num_heads: 2
temporal_axis: 10
fusion: "lf"
audio_positional_encoding: True
hidden_layers: 128
lp_only: False
audio_backbone: "eat" # MFCC, eat, xvectors, resnet, emotion2vec
middle_fusion_type: "self_cross_attention" # default, audio_refuse, video_refuse, self_attention, multi_attention, self_cross_attention
modality_dropout: 0.0
video_backbone: 'marlin'

