model_name: "celebvhq_marlin_deepfake_ft"
backbone: "marlin_vit_small_ytf"
training_datasets: ["DeepFakeTIMIT", "RAVDESS", "Forensics++"] #DeepFakeTIMIT,RAVDESS, Forensics++, DFDC, FakeAVCeleb
eval_datasets: ["Forensics++"]
task: "deepfake"
temporal_reduction: "mean"
learning_rate: 1.00e-3
seq_mean_pool: true
finetune: false
ir_layers: "conv"
num_heads: 2
temporal_axis: 10
fusion: "mf"
audio_positional_encoding: True
hidden_layers: 128
lp_only: False
audio_backbone: "MFCC" # MFCC, eat, xvectors, resnet, emotion2vec
middle_fusion_type: "default" # alternate1, self-attention, cross-attention